---
# task/install file for install_docker
- name: "Configure docker repository"
  ansible.builtin.include_role:
    name: ednxzu.manage_repositories
  vars:
    manage_repositories_enable_default_repo: false
    manage_repositories_enable_custom_repo: true
    manage_repositories_custom_repo: "{{ install_docker_repository }}"

- name: "Install docker packages"
  ansible.builtin.include_role:
    name: ednxzu.manage_apt_packages
  vars:
    manage_apt_packages_list: "{{ install_docker_packages }}"
