---
# task/install_python_docker file for docker
- name: "Install docker packages"
  ansible.builtin.include_role:
    name: ednz_cloud.manage_apt_packages
  vars:
    manage_apt_packages_list: "{{ install_docker_python_packages_list }}"
