---
name: end-to-end-tests
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
    branches:
      - main

jobs:
  retrieve-credentials:
    name: Retrieve Credentials
    runs-on: ubuntu-latest
    outputs:
      registry-username: ${{ steps.import-secrets.outputs.GITEA_ACTIONS_USERNAME }}
      registry-token: ${{ steps.import-secrets.outputs.GITEA_ACTIONS_TOKEN }}
    steps:
      - name: Get secrets from vault
        id: import-secrets
        uses: hashicorp/vault-action@v3
        with:
          url: "https://vault.ednz.fr"
          method: approle
          roleId: ${{ secrets.VAULT_APPROLE_ID }}
          secretId: ${{ secrets.VAULT_APPROLE_SECRET_ID }}
          secrets: |
            kv/data/applications/gitea/users/actions username | GITEA_ACTIONS_USERNAME ;
            kv/data/applications/gitea/users/actions token_write | GITEA_ACTIONS_TOKEN ;

  end_to_end_test:
    name: End to End Test
    needs: retrieve-credentials
    strategy:
      matrix:
        test_os:
          [
            "Debian 11 bullseye",
            "Debian 12 bookworm",
            "Ubuntu 20.04 LTS Focal Fossa",
            "Ubuntu 22.04 LTS Jammy Jellyfish",
            "Ubuntu 24.04 LTS Noble Numbat",
          ]
        scenario: ["default", "install_all"]
    uses: https://git.ednz.fr/github-actions/library/.gitea/workflows/molecule-e2e-test.yml@v0.1.0
    with:
      role: manage_repositories
      scenario: ${{ matrix.scenario }}
      test_os: ${{ matrix.test_os }}
    secrets:
      GITEA_ACTIONS_USERNAME: ${{ needs.retrieve-credentials.outputs.registry-username }}
      GITEA_ACTIONS_TOKEN: ${{ needs.retrieve-credentials.outputs.registry-token }}
