---
# handlers file for install_docker
- name: "Enable docker service"
  ansible.builtin.service:
    name: docker
    enabled: true
  listen: "systemctl-enable-docker"

- name: "Reload docker service"
  ansible.builtin.service:
    name: docker
    state: reloaded
  listen: "systemctl-reload-docker"
  when: install_docker_start_service
