---
- name: Prepare
  hosts: all
  tasks:
    - name: "Install pip3 packages"
      ansible.builtin.include_role:
        name: ednz_cloud.manage_apt_packages
      vars:
        manage_apt_packages_list:
          - name: python3-pip
            version: latest
            state: present
